name: Generate YOLO Badge

on:
  push:
    branches:
      - main

jobs:
  generate-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add YOLO Badge to README
        run: |
          echo '## YOLO Badge' >> README.md
          echo '![YOLO Badge](https://github.com/xlyoaz/xlyoaz/yolo.png)' >> README.md
      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Add YOLO Badge'
          git push
